#!/bin/bash
#
# On Ubuntu, install Firefox from Mozilla's PPA repo
# instead of from Canonical's "sanp" repo
#

# Add Mozilla repo
sudo add-apt-repository -y ppa:mozillateam/ppa

# Make Mozilla PPA version preferred
echo '
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001
' | sudo tee /etc/apt/preferences.d/mozilla-firefox

# Set auto install Firefox upgrades
echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox

# Install Firefox
sudo apt install -y --target-release 'o=LP-PPA-mozillateam' firefox

#::END::
