#!/bin/bash
#
# Get current JAVA JDK directory
# 
# author: Aldrin Edison Baroi
#

# Checks if JDK is installed
# Works on linux-gnu, solaris*, darwin*

[ $(which javac > /dev/null; echo $?) = 1 ] &&  echo "JDK is not installed" && exit 1

case $OSTYPE in
	linux-gnu|solaris*)
		# For Debian, Ubuntu, Redhat, CentOS, Solaris, OpenIndiana
		dirname $(dirname $(readlink -f $(which javac)))
		;;
	darwin*)
		# For MAX OS X
		/usr/libexec/java_home
		;;
	*)
		echo "JDK directory detection code not impleted for OS type [$OSTYPE]"
		exit 1
		;;
esac
#::END::
